version: '3.8'

services:
  user-service:
    container_name: ${SERVICE_ID}
    build: .
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - user-service-mysql
    environment:
      - DB_HOST=user-service-mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - traefik-network

  user-service-mysql:
    container_name: ${SERVICE_ID}-db
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --bind-address=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - traefik-network

volumes:
  mysql_data:

networks:
  traefik-network:
    name: traefik-network